name: histo_seg
channels:
- defaults
- conda-forge
- pytorch
- nvidia
dependencies:
- absl-py=2.0.0
- aiohttp=3.8.6
- aiohttp-retry=2.8.3
- aiosignal=1.3.1
- albumentations=1.3.1
- amqp=5.1.1
- antlr-python-runtime=4.9.3
- aom=3.6.1
- appdirs=1.4.4
- async-timeout=4.0.3
- asyncssh=2.14.0
- atk-1.0=2.38.0
- atpublic=3.0.1
- attrs=23.1.0
- backports=1.0
- backports.functools_lru_cache=1.6.5
- backports.zoneinfo=0.2.1
- billiard=4.1.0
- blinker=1.6.3
- blosc=1.21.5
- brotli=1.1.0
- brotli-bin=1.1.0
- brotli-python=1.1.0
- brunsli=0.1
- bzip2=1.0.8
- c-ares=1.20.1
- c-blosc2=2.10.5
- ca-certificates=2023.7.22
- cachetools=5.3.1
- cairo=1.18.0
- celery=5.3.4
- certifi=2023.7.22
- cffi=1.16.0
- cfgv=3.3.1
- charls=2.4.2
- charset-normalizer=3.3.0
- clearml=1.13.1
- click=8.1.7
- click-didyoumean=0.3.0
- click-plugins=1.1.1
- click-repl=0.3.0
- colorama=0.4.6
- configobj=5.0.8
- contourpy=1.1.1
- cryptography=41.0.4
- cycler=0.12.1
- dav1d=1.2.1
- decorator=5.1.1
- dictdiffer=0.9.0
- diskcache=5.6.3
- distlib=0.3.7
- distro=1.8.0
- dpath=2.1.6
- dulwich=0.21.6
- dvc=3.22.1
- dvc-data=2.16.4
- dvc-gdrive=2.20.0
- dvc-http=2.30.2
- dvc-objects=1.0.1
- dvc-render=0.6.0
- dvc-studio-client=0.15.0
- dvc-task=0.3.0
- et_xmlfile=1.1.0
- exceptiongroup=1.1.3
- expat=2.5.0
- ffmpeg=6.0.0
- ffmpeg-python=0.2.0
- filelock=3.12.4
- flatten-dict=0.4.2
- flufl.lock=7.1
- font-ttf-dejavu-sans-mono=2.37
- font-ttf-inconsolata=3.000
- font-ttf-source-code-pro=2.038
- font-ttf-ubuntu=0.83
- fontconfig=2.14.2
- fonts-conda-ecosystem=1
- fonts-conda-forge=1
- fonttools=4.43.1
- freetype=2.12.1
- fribidi=1.0.10
- frozenlist=1.4.0
- fsspec=2023.9.2
- funcy=1.18
- furl=2.1.3
- future=0.18.3
- gdk-pixbuf=2.42.10
- gettext=0.21.1
- giflib=5.2.1
- gitdb=4.0.10
- gitpython=3.1.40
- gmp=6.2.1
- gnutls=3.7.8
- google-api-core=2.12.0
- google-api-python-client=2.104.0
- google-auth=2.23.3
- google-auth-httplib2=0.1.1
- google-auth-oauthlib=1.0.0
- googleapis-common-protos=1.61.0
- grandalf=0.7
- graphite2=1.3.13
- graphviz=8.1.0
- grpcio=1.58.1
- gtk2=2.24.33
- gts=0.7.6
- harfbuzz=8.2.1
- hdf5=1.14.2
- httplib2=0.22.0
- hydra-core=1.3.2
- icu=73.2
- identify=2.5.30
- idna=3.4
- imagecodecs=2023.9.18
- imageio=2.31.5
- importlib-metadata=6.8.0
- importlib_resources=6.1.0
- iniconfig=2.0.0
- iterative-telemetry=0.0.8
- jasper=4.0.0
- joblib=1.3.2
- jsonschema=4.19.1
- jsonschema-specifications=2023.7.1
- jxrlib=1.1
- kiwisolver=1.4.5
- kombu=5.3.2
- krb5=1.21.2
- lame=3.100
- lazy_loader=0.3
- lcms2=2.15
- lerc=4.0.0
- libabseil=20230802.1
- libaec=1.1.2
- libass=0.17.1
- libavif16=1.0.1
- libblas=3.9.0
- libbrotlicommon=1.1.0
- libbrotlidec=1.1.0
- libbrotlienc=1.1.0
- libcblas=3.9.0
- libcurl=8.4.0
- libcxx=16.0.6
- libdeflate=1.19
- libedit=3.1.20191231
- libev=4.33
- libexpat=2.5.0
- libffi=3.4.2
- libgd=2.3.3
- libgfortran=5.0.0
- libgfortran5=13.2.0
- libgit2=1.7.1
- libglib=2.78.0
- libgrpc=1.58.1
- libiconv=1.17
- libidn2=2.3.4
- libjpeg-turbo=3.0.0
- liblapack=3.9.0
- liblapacke=3.9.0
- libnghttp2=1.52.0
- libopenblas=0.3.24
- libopencv=4.8.1
- libopenvino=2023.1.0
- libopenvino-arm-cpu-plugin=2023.1.0
- libopenvino-auto-batch-plugin=2023.1.0
- libopenvino-auto-plugin=2023.1.0
- libopenvino-hetero-plugin=2023.1.0
- libopenvino-ir-frontend=2023.1.0
- libopenvino-onnx-frontend=2023.1.0
- libopenvino-paddle-frontend=2023.1.0
- libopenvino-pytorch-frontend=2023.1.0
- libopenvino-tensorflow-frontend=2023.1.0
- libopenvino-tensorflow-lite-frontend=2023.1.0
- libopus=1.3.1
- libpng=1.6.39
- libprotobuf=4.24.3
- libre2-11=2023.06.02
- librsvg=2.56.3
- libsqlite=3.43.2
- libssh2=1.11.0
- libtasn1=4.19.0
- libtiff=4.6.0
- libtool=2.4.7
- libunistring=0.9.10
- libvpx=1.13.1
- libwebp=1.3.2
- libwebp-base=1.3.2
- libxcb=1.15
- libxml2=2.11.5
- libzlib=1.2.13
- libzopfli=1.0.3
- llvm-openmp=17.0.3
- lz4-c=1.9.4
- markdown=3.5
- markdown-it-py=3.0.0
- markupsafe=2.1.3
- matplotlib=3.8.0
- matplotlib-base=3.8.0
- mdurl=0.1.0
- multidict=6.0.4
- munkres=1.1.4
- nanotime=0.5.2
- ncurses=6.4
- nettle=3.8.1
- networkx=3.2
- nodeenv=1.8.0
- numpy=1.26.0
- oauth2client=4.1.3
- oauthlib=3.2.2
- omegaconf=2.3.0
- opencv=4.8.1
- openh264=2.3.1
- openjpeg=2.5.0
- openpyxl=3.1.2
- openssl=3.1.3
- orderedmultidict=1.0.1
- orjson=3.9.8
- p11-kit=0.24.1
- packaging=23.2
- pango=1.50.14
- pathlib2=2.3.7.post1
- pathspec=0.11.2
- pcre2=10.40
- pip=23.3
- pixman=0.42.2
- pkgutil-resolve-name=1.3.10
- platformdirs=3.11.0
- pluggy=1.3.0
- pre-commit=3.5.0
- prompt-toolkit=3.0.39
- prompt_toolkit=3.0.39
- psutil=5.9.5
- pthread-stubs=0.4
- pugixml=1.13
- py-opencv=4.8.1
- pyasn1=0.5.0
- pyasn1-modules=0.3.0
- pycparser=2.21
- pydot=1.4.2
- pydrive2=1.17.0
- pygit2=1.13.1
- pygments=2.16.1
- pygtrie=2.5.0
- pyjwt=2.4.0
- pyopenssl=23.2.0
- pyparsing=3.1.1
- pysocks=1.7.1
- pytest=7.4.2
- python=3.11.6
- python-dateutil=2.8.2
- python-gssapi=1.8.3
- python-tzdata=2023.3
- python_abi=3.11
- pytz=2023.3.post1
- pyu2f=0.1.5
- pywavelets=1.4.1
- pywin32-on-windows=0.1.0
- pyyaml=6.0.1
- qudida=0.0.4
- rav1e=0.6.6
- re2=2023.06.02
- readline=8.2
- referencing=0.30.2
- requests=2.31.0
- requests-oauthlib=1.3.1
- rich=13.6.0
- rpds-py=0.10.6
- rsa=4.9
- ruamel.yaml=0.17.38
- ruamel.yaml.clib=0.2.7
- scikit-image=0.22.0
- scikit-learn=1.3.1
- scipy=1.11.3
- scmrepo=1.4.0
- setuptools=68.2.2
- shortuuid=1.0.11
- shtab=1.6.4
- six=1.16.0
- smmap=3.0.5
- snappy=1.1.10
- sqltrie=0.8.0
- svt-av1=1.7.0
- tabulate=0.9.0
- tbb=2021.10.0
- tensorboard=2.14.1
- tensorboard-data-server=0.7.0
- threadpoolctl=3.2.0
- tifffile=2023.9.26
- tk=8.6.13
- tomli=2.0.1
- tomlkit=0.12.1
- tornado=6.3.3
- tqdm=4.66.1
- typing-extensions=4.8.0
- typing_extensions=4.8.0
- tzdata=2023c
- ukkonen=1.0.1
- uritemplate=4.1.1
- vine=5.0.0
- virtualenv=20.24.4
- voluptuous=0.13.1
- wcwidth=0.2.8
- werkzeug=3.0.0
- wheel=0.41.2
- x264=1!164.3095
- x265=3.5
- xorg-libxau=1.0.11
- xorg-libxdmcp=1.1.3
- xz=5.2.6
- yaml=0.2.5
- yarl=1.9.2
- zc.lockfile=3.0.post1
- zfp=1.0.0
- zipp=3.17.0
- zlib=1.2.13
- zlib-ng=2.0.7
- zstd=1.5.5
- pip:
  - aiocache==0.12.0
  - anyio==3.7.1
  - arel==0.2.0
  - async-asgi-testclient==1.4.11
  - beautifulsoup4==4.12.2
  - bidict==0.22.1
  - configspace==0.7.1
  - distinctipy==1.2.3
  - efficientnet-pytorch==0.7.1
  - executing==2.0.0
  - fastapi==0.104.0
  - giturlparse==0.12.0
  - h11==0.14.0
  - hpbandster==0.7.4
  - httptools==0.6.1
  - huggingface-hub==0.18.0
  - imutils==0.5.4
  - jinja2==3.1.2
  - jsonpatch==1.33
  - jsonpointer==2.4
  - lightning-utilities==0.9.0
  - more-itertools==10.1.0
  - mpmath==1.3.0
  - munch==4.0.0
  - netifaces==0.11.0
  - numerize==0.12
  - pandas==1.5.2
  - patsy==0.5.3
  - pillow==9.5.0
  - pretrainedmodels==0.7.4
  - protobuf==3.20.3
  - ptable==0.9.2
  - pydantic==1.10.7
  - pydicom==2.4.3
  - pynrrd==0.4.3
  - pyro4==4.82
  - python-dotenv==0.21.1
  - python-json-logger==2.0.7
  - python-magic==0.4.27
  - python-multipart==0.0.5
  - pytorch-lightning==2.0.9
  - requests-toolbelt==0.10.1
  - safetensors==0.4.0
  - scikit-video==1.1.11
  - segmentation-models-pytorch==0.3.3
  - serpent==1.41
  - shapely==1.8.5.post1
  - simpleitk==2.3.0
  - sniffio==1.3.0
  - soupsieve==2.5
  - starlette==0.27.0
  - statsmodels==0.14.0
  - stringcase==1.2.0
  - supervisely==6.71.19
  - sympy==1.12
  - timm==0.9.2
  - torch==2.1.0
  - torchmetrics==1.2.0
  - torchvision==0.16.0
  - trimesh==3.23.5
  - urllib3==1.26.15
  - uvicorn==0.23.2
  - uvloop==0.18.0
  - varname==0.12.0
  - watchfiles==0.21.0
  - watchgod==0.6
  - websockets==10.4
